bb_tracker:
   ros__parameters:
      time_to_lost: 1500
      unconfirmed_ttl: 1000
      lost_ttl: 2000
      track_thresh: 0.5
      high_thresh: 0.6
      match_thresh: 0.8
      fixed_frame: sensors_home
      show_img_projection: false