bb_tracker:
   ros__parameters:
      max_dt_past: 2000
      time_to_lost: 1500
      unconfirmed_ttl: 1000
      lost_ttl: 2000
      track_thresh: 0.5
      high_thresh: 0.6
      match_thresh: 0.8
      fixed_frame: sensors_home
      show_img_projection: true
      left_handed_system: true
      # P0 3D
      mul_p03d: [
         2.,2.,      # position
         10.,        # yaw
         1.,1.,5.,   # size
         10.,10.     # velocity
         ]
      # P0 2D
      mul_p02d: [
         10.,10.,    # position
         90.,        # yaw
         1.,1.,1.,   # size
         10.,10.     # velocity
         ]
      # V1
      mul_process_noise: [
         1.,1.,      # position
         1.,         # yaw
         1.,1.,1.,   # size
         1.,1.       # velocity
         ]
      # V2 3D
      mul_mn3d: [
         1.,1.,      # position
         1.,         # yaw
         1.,1.,1.    # size
         ]
      # V2 2D
      mul_mn2d: [
         10.,10.,    # position
         10.,10.,    # semi-axes
         60.          # theta
         ]