bb_tracker:
   ros__parameters:
      fixed_frame: map
      # Visualization
      show_img_projection: false
      show_covariance: false
      points_per_track: 120
      # Detection
      left_handed_system: true
      max_dt_past: 2000
      camera_list: [
         "/carla/cross_s/rgb/camera_info",
         "/carla/int_road_s/rgb/camera_info",
         "/carla/near_station_s/rgb_w_station/camera_info",
         "/carla/near_station_s/rgb_w_street/camera_info",
         "/carla/cross_s/thermal/camera_info",
         "/carla/int_road_s/thermal/camera_info", 
         "/carla/near_station_s/thermal/camera_info"
         ]
      image_list: [
         "/carla/cross_s/rgb/image",
         "/carla/int_road_s/rgb/image",
         "/carla/near_station_s/rgb_w_station/image",
         "/carla/near_station_s/rgb_w_street/image",
         "/carla/cross_s/thermal/image",
         "/carla/int_road_s/thermal/image", 
         "/carla/near_station_s/thermal/image"
         ]
      detection2d_list: [
         "/carla/cross_s/rgb/det2d",
         "/carla/int_road_s/rgb/det2d",
         "/carla/near_station_s/rgb_w_station/det2d",
         "/carla/near_station_s/rgb_w_street/det2d",
         "/carla/cross_s/thermal/det2d",
         "/carla/int_road_s/thermal/det2d", 
         "/carla/near_station_s/thermal/det2d"
      ]
      detection3d_list: [
         "bytetrack/detections3d",
         #"second_topic"
      ]
      # Tracker Time
      time_to_lost: 1000
      unconfirmed_ttl: 1000
      lost_ttl: 2000
      # Tracker Thresh
      track_thresh: 0.5
      high_thresh: 0.5
      match_thresh: 0.7
 
      # Kalman Filter (consider cm, degrees, cm/s and degrees/s as MU)
      # P0 3D
      mul_p03d: [
         15.,15.,       # position
         10.,           # yaw
         10.,10.,30.,   # size
         150.,18.       # velocity
         ]
      # P0 2D
      mul_p02d: [
         15.,15.,       # position
         10.,           # yaw
         1.,1.,10.,     # size
         100.,15.       # velocity
         ]
      # V1
      mul_process_noise: [
         1.,1.,      # position
         1.,         # yaw
         1.,1.,1.,   # size
         10.,5.      # velocity
         ]
      # V2 3D
      mul_mn3d: [
         10.,10.,       # position
         10.,           # yaw
         45.,45.,45.    # size
         ]
      # V2 2D
      mul_mn2d: [
         10.,10.,       # position
         100.,100.,     # semi-axes
         45.            # theta
         ]