bb_benchmark:
   ros__parameters:
      fps: 10
      match_thresh: 0.7
      fixed_frame: map
      show_range: true
      alpha_range: 0.1
      camera_list: [
         "/carla/sensors_home/static_rgb_camera/camera_info", 
         "/carla/sensors_home/static_termic_camera/camera_info"
         ]
      camera_max_distances: [
         30, 50
      ]
      lidar_list: [
         "sensors_home/static_lidar"
      ]
      lidar_max_distances: [
         30
      ]
      